name: easy_reading
description: A flashcard app with AI integration for enhanced learning
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.3+8
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^13.0.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # Utils
  intl: ^0.18.1
  logger: ^2.0.2
  
  # Firebase
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  bloc_test: ^9.1.5
  mockito: ^5.4.4
  fake_cloud_firestore: ^2.4.8
  firebase_auth_mocks: ^0.13.0
  integration_test:
    sdk: flutter
  test: ^1.24.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
