global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'easyreading-api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Configurar alertmanager quando necessário
          # - 'alertmanager:9093'

rule_files:
  # Adicionar regras de alerta quando necessário
  # - "alert.rules"
