name: Android Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'
      
      # Configuração do cache para o Gradle
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      # Configuração do cache para o pub
      - name: Flutter pub cache
        uses: actions/cache@v3
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
            
      # Instalação das dependências Flutter
      - name: Get dependencies
        run: flutter pub get
        
      # Análise do código
      - name: Analyze code
        run: flutter analyze
      
      # Execução dos testes
      - name: Run tests
        run: flutter test
      
      # Build do APK e análise de tamanho
      - name: Build and analyze APK
        run: flutter build apk --analyze-size
        
      # Build do AppBundle para Google Play
      - name: Build AppBundle
        run: flutter build appbundle --analyze-size
      
      # Upload dos artefatos de build
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
      - name: Upload AppBundle
        uses: actions/upload-artifact@v3
        with:
          name: release-bundle
          path: build/app/outputs/bundle/release/app-release.aab
